export * from "./phone/Phone"
export * from "./about/About"
export * from "./home/Home"
export * from "./phone/PhoneDetail"
export * from "./login/Login"
export * from "./register/Register"
export * from "./order/Order"
export * from "./checkout/Checkout"